### ISSUE TITLE
Does not compile with newest monogame

### ISSUE THREAD

**Issue by bosoni** [RonenNess/GeonBit#2]
Matrix's Scale and Rotation getters(properties) have been removed, so cant compile with newest monogame.

https://github.com/MonoGame/MonoGame/issues/5553

**Comment by RonenNess** [comment]
I'll take a look when I'll have time, probably during the next weekend..
Thanks!

**Comment by RonenNess** [comment]
Fixed, I hope I caught all the places, If not let me know ;)

Thanks!
